apiVersion: v1
kind: Service
metadata:
  name: nodejs-welcome-service
spec:
  selector:
    app: nodejs-welcome-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer