apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-welcome-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs-welcome-app
  template:
    metadata:
      labels:
        app: nodejs-welcome-app
    spec:
      containers:
      - name: nodejs-welcome-app
        image: your-dockerhub-username/nodejs-welcome-app:latest
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi